apiVersion: v1
kind: Service
metadata:
  namespace: hub-dev
  name: ms-hub-service
  labels:
    app: ms-hub-service
spec:
  type: ClusterIP
  selector:
    app: ms-hub
  ports:
    - port: 3349
      targetPort: 3349
      name: http
