apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: hub-dev
images:
- name: ms-hub-rabbit-mongo
  newName: miguekos1233/ms-hub-rabbit-mongo
  newTag: 4ca1df2a5982139849b0bac355644c949bb09c80
