apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: hub-dev
images:
- name: ms-hub
  newName: miguekos1233/ms-hub-rabbit-mongo
  newTag: "1.3"
