apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: hub-dev
images:
- name: ms-hub
  newName: miguekos1233/ms-hub-rabbit-mongo
  newTag: "1.3"
- name: ms-hub-rabbit-mongo
  newName: /ms-hub-rabbit-mongo
  newTag: 63fbd450b8b9be4133c926b9774a8f4818d51452
