apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: app-utils
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    name: "mongodb-service"
  selector:
    name: mongodb
    app: app-utils