apiVersion: v1
kind: Service
metadata:
  name: utils
  labels:
    name: utils
    app: app-utils
spec:
  type: NodePort
  ports:
  - port: 3346
    targetPort: 3346
    nodePort: 31000
    name: "utils-service"
  selector:
    name: utils
    app: app-utils