apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
  labels:
    app: app-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      name: utils
      app: app-utils
  template:
    metadata:
      name: utils
      labels:
        name: utils
        app: app-utils
    spec:
      containers:
      - name: utils
        image: miguekos1233/apputils:1.0
        command: ["pm2-runtime"]
        args: ["server.config.js", "--env", "production"]
        ports:
        - containerPort: 3346
          name: utils
